---
# ref v2.x https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties
#debug: true
spring:
  application:
    name: springbootDemoWeb
#  profiles:
#    active: dev
#    default: default
#    include: common2,common1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labdb
    username: developer
    password: developer
  banner:
    charset: UTF-8
    location: classpath:config/banner/defaultBanner.txt
server:
  port: 8080
  servlet:
    session:
      timeout: 30  
    contextPath: /demoyml

app:
  banner: Hunter's banner for SpringBoot
developer:
  name: main common Hunter Chen ${spring.application.name}
  mail: hunterflag@gmail.com
  mobile: +886 918 367 286
...
---
spring:
  profile: default    
  banner:
    location: classpath:config/banner/devBanner.txt
developer:
  name: main default Hunter Chen ${spring.application.name}
  mail: hunterflag@gmail.com
  mobile: +886 918 367 286
...
---
spring:
  profile: dev
  application:
    name: springbootDemoWeb on DEV mode
#  banner:
#    location: classpath:config/banner/devBanner.txt
  config:
    import: classpath:config/application-common1.yml

server:
  port: 9090
developer:
  name: main dev Hunter Chen ${spring.application.name}
...