spring:
  profiles:
    active:
      - testyml
company:
  name: New Subway PC Studio in common block in application.yml
---
spring:
  profiles:
    active:
company:
  name: New Subway PC Studio in test block in application.yml